package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.71

import (
	"context"

	"github.com/ekhodzitsky/go-ozon-marketplace/pkg/middleware"
	"github.com/ekhodzitsky/go-ozon-marketplace/services/api-gateway/graph/model"
	"github.com/ekhodzitsky/go-ozon-marketplace/services/api-gateway/internal/usecase"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, email string, password string, name string) (string, error) {
	return usecase.Register(ctx, r.UserService, email, password, name, r.CallTimeout)
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string) (string, error) {
	return usecase.Login(ctx, r.UserService, email, password, r.CallTimeout)
}

// CreateProduct is the resolver for the createProduct field.
func (r *mutationResolver) CreateProduct(ctx context.Context, name string, description string, price float64, categories []string) (string, error) {
	return usecase.CreateProduct(ctx, r.CatalogService, name, description, price, categories, r.CallTimeout)
}

// CreateOrder is the resolver for the createOrder field.
func (r *mutationResolver) CreateOrder(ctx context.Context, items []*model.OrderItemInput) (string, error) {
	return usecase.CreateOrder(ctx, r.OrderService, r.CatalogService, r.AnalyticsService, r.ABExperiments, items, r.CallTimeout, r.QueryTimeout)
}

// CancelOrder is the resolver for the cancelOrder field.
func (r *mutationResolver) CancelOrder(ctx context.Context, orderID string) (bool, error) {
	return usecase.CancelOrder(ctx, r.OrderService, orderID, r.CallTimeout, r.QueryTimeout)
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	return usecase.Me(ctx, r.UserService, r.QueryTimeout)
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	return usecase.GetUser(ctx, r.UserService, id, r.QueryTimeout)
}

// Product is the resolver for the product field.
func (r *queryResolver) Product(ctx context.Context, id string) (*model.Product, error) {
	return usecase.GetProduct(ctx, r.CatalogService, id, r.QueryTimeout)
}

// SearchProducts is the resolver for the searchProducts field.
func (r *queryResolver) SearchProducts(ctx context.Context, query string, page *int32, pageSize *int32) (*model.ProductConnection, error) {
	return usecase.SearchProducts(ctx, r.CatalogService, query, page, pageSize, r.QueryTimeout)
}

// Order is the resolver for the order field.
func (r *queryResolver) Order(ctx context.Context, id string) (*model.Order, error) {
	return usecase.GetOrder(ctx, r.OrderService, id, r.QueryTimeout)
}

// Orders is the resolver for the orders field.
func (r *queryResolver) Orders(ctx context.Context, userID string, page *int32, pageSize *int32) (*model.OrderConnection, error) {
	return usecase.ListOrders(ctx, r.OrderService, userID, page, pageSize, r.QueryTimeout)
}

// Inventory is the resolver for the inventory field.
func (r *queryResolver) Inventory(ctx context.Context, productID string) (*model.Inventory, error) {
	return usecase.GetInventory(ctx, r.InventoryService, productID, r.QueryTimeout)
}

// FeatureFlags is the resolver for the featureFlags field.
func (r *queryResolver) FeatureFlags(ctx context.Context) (*model.FeatureFlags, error) {
	userID, _ := middleware.GetUserID(ctx)
	return usecase.FeatureFlags(ctx, r.Resolver.FeatureFlags, userID)
}

// AbTestAssignments is the resolver for the abTestAssignments field.
func (r *queryResolver) AbTestAssignments(ctx context.Context, userID string) ([]*model.ABTestAssignment, error) {
	return usecase.AbTestAssignments(ctx, r.ABExperiments, userID)
}

// OrderStatusChanged is the resolver for the orderStatusChanged field.
func (r *subscriptionResolver) OrderStatusChanged(ctx context.Context, userID string) (<-chan *model.Order, error) {
	return usecase.OrderStatusChanged(ctx, r.Redis, userID)
}

// InventoryChanged is the resolver for the inventoryChanged field.
func (r *subscriptionResolver) InventoryChanged(ctx context.Context, productID string) (<-chan *model.Inventory, error) {
	return usecase.InventoryChanged(ctx, r.Redis, productID)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
