package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.71

import (
	"context"
	"fmt"

	catalogv1 "github.com/ekhodzitsky/go-ozon-marketplace/api/gen/go/catalog/v1"
	inventoryv1 "github.com/ekhodzitsky/go-ozon-marketplace/api/gen/go/inventory/v1"
	orderv1 "github.com/ekhodzitsky/go-ozon-marketplace/api/gen/go/order/v1"
	userv1 "github.com/ekhodzitsky/go-ozon-marketplace/api/gen/go/user/v1"
	"github.com/ekhodzitsky/go-ozon-marketplace/pkg/middleware"
	"github.com/ekhodzitsky/go-ozon-marketplace/pkg/validation"
	"github.com/ekhodzitsky/go-ozon-marketplace/services/api-gateway/graph/model"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, email string, password string, name string) (string, error) {
	if err := validation.ValidateEmail(email); err != nil {
		return "", fmt.Errorf("invalid input: %w", err)
	}
	if err := validation.ValidatePassword(password); err != nil {
		return "", fmt.Errorf("invalid input: %w", err)
	}
	if err := validation.ValidateName(name); err != nil {
		return "", fmt.Errorf("invalid input: %w", err)
	}
	ctx, cancel := r.withTimeout(ctx)
	defer cancel()
	resp, err := r.UserService.Register(ctx, &userv1.RegisterRequest{
		Email:    email,
		Password: password,
		Name:     name,
	})
	if err != nil {
		return "", err
	}
	return resp.UserId, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string) (string, error) {
	if err := validation.ValidateEmail(email); err != nil {
		return "", fmt.Errorf("invalid input: %w", err)
	}
	if err := validation.ValidatePassword(password); err != nil {
		return "", fmt.Errorf("invalid input: %w", err)
	}
	ctx, cancel := r.withTimeout(ctx)
	defer cancel()
	resp, err := r.UserService.Login(ctx, &userv1.LoginRequest{
		Email:    email,
		Password: password,
	})
	if err != nil {
		return "", err
	}
	return resp.Token, nil
}

// CreateProduct is the resolver for the createProduct field.
func (r *mutationResolver) CreateProduct(ctx context.Context, name string, description string, price float64, categories []string) (string, error) {
	if err := validation.ValidateName(name); err != nil {
		return "", fmt.Errorf("invalid input: %w", err)
	}
	if err := validation.ValidatePrice(price); err != nil {
		return "", fmt.Errorf("invalid input: %w", err)
	}
	ctx, cancel := r.withTimeout(ctx)
	defer cancel()
	resp, err := r.CatalogService.CreateProduct(ctx, &catalogv1.CreateProductRequest{
		Name:        name,
		Description: description,
		Price:       price,
		Categories:  categories,
	})
	if err != nil {
		return "", err
	}
	return resp.ProductId, nil
}

// CreateOrder is the resolver for the createOrder field.
func (r *mutationResolver) CreateOrder(ctx context.Context, userID string, items []*model.OrderItemInput) (string, error) {
	protoItems := make([]*orderv1.OrderItem, len(items))
	for i, item := range items {
		if err := validation.ValidateQuantity(item.Quantity); err != nil {
			return "", fmt.Errorf("invalid input: %w", err)
		}
		if err := validation.ValidatePrice(item.Price); err != nil {
			return "", fmt.Errorf("invalid input: %w", err)
		}
		protoItems[i] = &orderv1.OrderItem{
			ProductId: item.ProductID,
			Quantity:  item.Quantity,
			Price:     item.Price,
		}
	}
	ctx, cancel := r.withTimeout(ctx)
	defer cancel()
	resp, err := r.OrderService.CreateOrder(ctx, &orderv1.CreateOrderRequest{
		UserId: userID,
		Items:  protoItems,
	})
	if err != nil {
		return "", err
	}
	return resp.OrderId, nil
}

// CancelOrder is the resolver for the cancelOrder field.
func (r *mutationResolver) CancelOrder(ctx context.Context, orderID string) (bool, error) {
	ctx, cancel := r.withTimeout(ctx)
	defer cancel()
	_, err := r.OrderService.CancelOrder(ctx, &orderv1.CancelOrderRequest{
		OrderId: orderID,
	})
	if err != nil {
		return false, err
	}
	return true, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	userID, ok := middleware.GetUserID(ctx)
	if !ok {
		return nil, fmt.Errorf("unauthenticated")
	}
	ctx, cancel := r.withQueryTimeout(ctx)
	defer cancel()
	resp, err := r.UserService.GetUser(ctx, &userv1.GetUserRequest{
		UserId: userID,
	})
	if err != nil {
		return nil, err
	}
	return &model.User{
		ID:        resp.UserId,
		Email:     resp.Email,
		Name:      resp.Name,
		CreatedAt: resp.CreatedAt,
	}, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	ctx, cancel := r.withQueryTimeout(ctx)
	defer cancel()
	resp, err := r.UserService.GetUser(ctx, &userv1.GetUserRequest{
		UserId: id,
	})
	if err != nil {
		return nil, err
	}
	return &model.User{
		ID:        resp.UserId,
		Email:     resp.Email,
		Name:      resp.Name,
		CreatedAt: resp.CreatedAt,
	}, nil
}

// Product is the resolver for the product field.
func (r *queryResolver) Product(ctx context.Context, id string) (*model.Product, error) {
	ctx, cancel := r.withQueryTimeout(ctx)
	defer cancel()
	resp, err := r.CatalogService.GetProduct(ctx, &catalogv1.GetProductRequest{
		ProductId: id,
	})
	if err != nil {
		return nil, err
	}
	return protoProductToModel(resp.Product), nil
}

// SearchProducts is the resolver for the searchProducts field.
func (r *queryResolver) SearchProducts(ctx context.Context, query string, page *int32, pageSize *int32) (*model.ProductConnection, error) {
	ctx, cancel := r.withQueryTimeout(ctx)
	defer cancel()
	req := &catalogv1.SearchProductsRequest{
		Query: query,
	}
	if page != nil {
		req.Page = *page
	}
	if pageSize != nil {
		if err := validation.ValidatePageSize(*pageSize); err != nil {
			return nil, fmt.Errorf("invalid input: %w", err)
		}
		req.PageSize = *pageSize
	}
	resp, err := r.CatalogService.SearchProducts(ctx, req)
	if err != nil {
		return nil, err
	}
	products := make([]*model.Product, len(resp.Products))
	for i, p := range resp.Products {
		products[i] = protoProductToModel(p)
	}
	return &model.ProductConnection{
		Products: products,
		Total:    resp.Total,
	}, nil
}

// Order is the resolver for the order field.
func (r *queryResolver) Order(ctx context.Context, id string) (*model.Order, error) {
	ctx, cancel := r.withQueryTimeout(ctx)
	defer cancel()
	resp, err := r.OrderService.GetOrder(ctx, &orderv1.GetOrderRequest{
		OrderId: id,
	})
	if err != nil {
		return nil, err
	}
	return protoOrderToModel(resp.Order), nil
}

// Orders is the resolver for the orders field.
func (r *queryResolver) Orders(ctx context.Context, userID string, page *int32, pageSize *int32) (*model.OrderConnection, error) {
	ctx, cancel := r.withQueryTimeout(ctx)
	defer cancel()
	req := &orderv1.ListOrdersRequest{
		UserId: userID,
	}
	if page != nil {
		req.Page = *page
	}
	if pageSize != nil {
		if err := validation.ValidatePageSize(*pageSize); err != nil {
			return nil, fmt.Errorf("invalid input: %w", err)
		}
		req.PageSize = *pageSize
	}
	resp, err := r.OrderService.ListOrders(ctx, req)
	if err != nil {
		return nil, err
	}
	orders := make([]*model.Order, len(resp.Orders))
	for i, o := range resp.Orders {
		orders[i] = protoOrderToModel(o)
	}
	return &model.OrderConnection{
		Orders: orders,
		Total:  resp.Total,
	}, nil
}

// Inventory is the resolver for the inventory field.
func (r *queryResolver) Inventory(ctx context.Context, productID string) (*model.Inventory, error) {
	ctx, cancel := r.withQueryTimeout(ctx)
	defer cancel()
	resp, err := r.InventoryService.GetStock(ctx, &inventoryv1.GetStockRequest{
		ProductId: productID,
	})
	if err != nil {
		return nil, err
	}
	return &model.Inventory{
		ProductID: productID,
		Available: resp.Available,
		Reserved:  resp.Reserved,
	}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
