replicaCount: 2

image:
  repository: go-ozon-marketplace/notification-service
  pullPolicy: IfNotPresent
  tag: ""

service:
  type: ClusterIP
  grpcPort: 50056
  metricsPort: 51056

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
  hosts:
    - host: notification-service.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

env:
  GRPC_PORT: "50056"

secrets:
  jwtSecret: ""      # required
  postgresDSN: ""    # required

nodeSelector: {}
tolerations: []
affinity: {}
