replicaCount: 2

image:
  repository: go-ozon-marketplace/notification-service
  pullPolicy: IfNotPresent
  tag: ""

service:
  type: ClusterIP
  grpcPort: 50056
  metricsPort: 51056

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
  hosts:
    - host: notification-service.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

env:
  GRPC_PORT: "50056"
  KAFKA_BROKERS: "kafka:9092"
  KAFKA_TOPICS: "order-events"
  KAFKA_CONSUMER_GROUP: "notification-service"
  KAFKA_DLQ_TOPIC: "notification-dlq"
  SMTP_HOST: ""
  SMTP_PORT: "587"
  SMTP_FROM: "notifications@example.com"
  SMTP_USER: ""
  SMTP_PASSWORD: ""

secrets:
  jwtSecret: ""      # обязательно

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}
