// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ekhodzitsky/go-ozon-marketplace/services/analytics-service/internal/usecase (interfaces: AnalyticsUsecase)
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=mocks/mock_analytics_usecase.go github.com/ekhodzitsky/go-ozon-marketplace/services/analytics-service/internal/usecase AnalyticsUsecase
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/ekhodzitsky/go-ozon-marketplace/services/analytics-service/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockAnalyticsUsecase is a mock of AnalyticsUsecase interface.
type MockAnalyticsUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockAnalyticsUsecaseMockRecorder
	isgomock struct{}
}

// MockAnalyticsUsecaseMockRecorder is the mock recorder for MockAnalyticsUsecase.
type MockAnalyticsUsecaseMockRecorder struct {
	mock *MockAnalyticsUsecase
}

// NewMockAnalyticsUsecase creates a new mock instance.
func NewMockAnalyticsUsecase(ctrl *gomock.Controller) *MockAnalyticsUsecase {
	mock := &MockAnalyticsUsecase{ctrl: ctrl}
	mock.recorder = &MockAnalyticsUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnalyticsUsecase) EXPECT() *MockAnalyticsUsecaseMockRecorder {
	return m.recorder
}

// Flush mocks base method.
func (m *MockAnalyticsUsecase) Flush(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Flush", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Flush indicates an expected call of Flush.
func (mr *MockAnalyticsUsecaseMockRecorder) Flush(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Flush", reflect.TypeOf((*MockAnalyticsUsecase)(nil).Flush), ctx)
}

// GetDailyRevenue mocks base method.
func (m *MockAnalyticsUsecase) GetDailyRevenue(ctx context.Context, date string) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDailyRevenue", ctx, date)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDailyRevenue indicates an expected call of GetDailyRevenue.
func (mr *MockAnalyticsUsecaseMockRecorder) GetDailyRevenue(ctx, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDailyRevenue", reflect.TypeOf((*MockAnalyticsUsecase)(nil).GetDailyRevenue), ctx, date)
}

// TrackABTestEvent mocks base method.
func (m *MockAnalyticsUsecase) TrackABTestEvent(ctx context.Context, event domain.ABTestEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TrackABTestEvent", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// TrackABTestEvent indicates an expected call of TrackABTestEvent.
func (mr *MockAnalyticsUsecaseMockRecorder) TrackABTestEvent(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackABTestEvent", reflect.TypeOf((*MockAnalyticsUsecase)(nil).TrackABTestEvent), ctx, event)
}

// TrackEvent mocks base method.
func (m *MockAnalyticsUsecase) TrackEvent(ctx context.Context, eventType domain.EventType, aggregateID, payload, aggregationKey string, amount float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TrackEvent", ctx, eventType, aggregateID, payload, aggregationKey, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// TrackEvent indicates an expected call of TrackEvent.
func (mr *MockAnalyticsUsecaseMockRecorder) TrackEvent(ctx, eventType, aggregateID, payload, aggregationKey, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackEvent", reflect.TypeOf((*MockAnalyticsUsecase)(nil).TrackEvent), ctx, eventType, aggregateID, payload, aggregationKey, amount)
}
