// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ekhodzitsky/go-ozon-marketplace/services/analytics-service/internal/usecase (interfaces: EventRepository)
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=mocks/mock_event_repository.go github.com/ekhodzitsky/go-ozon-marketplace/services/analytics-service/internal/usecase EventRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/ekhodzitsky/go-ozon-marketplace/services/analytics-service/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockEventRepository is a mock of EventRepository interface.
type MockEventRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEventRepositoryMockRecorder
	isgomock struct{}
}

// MockEventRepositoryMockRecorder is the mock recorder for MockEventRepository.
type MockEventRepositoryMockRecorder struct {
	mock *MockEventRepository
}

// NewMockEventRepository creates a new mock instance.
func NewMockEventRepository(ctrl *gomock.Controller) *MockEventRepository {
	mock := &MockEventRepository{ctrl: ctrl}
	mock.recorder = &MockEventRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventRepository) EXPECT() *MockEventRepositoryMockRecorder {
	return m.recorder
}

// BatchInsert mocks base method.
func (m *MockEventRepository) BatchInsert(ctx context.Context, events []domain.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchInsert", ctx, events)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchInsert indicates an expected call of BatchInsert.
func (mr *MockEventRepositoryMockRecorder) BatchInsert(ctx, events any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchInsert", reflect.TypeOf((*MockEventRepository)(nil).BatchInsert), ctx, events)
}

// GetDailyRevenue mocks base method.
func (m *MockEventRepository) GetDailyRevenue(ctx context.Context, date string) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDailyRevenue", ctx, date)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDailyRevenue indicates an expected call of GetDailyRevenue.
func (mr *MockEventRepositoryMockRecorder) GetDailyRevenue(ctx, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDailyRevenue", reflect.TypeOf((*MockEventRepository)(nil).GetDailyRevenue), ctx, date)
}

// TrackABTestEvent mocks base method.
func (m *MockEventRepository) TrackABTestEvent(ctx context.Context, event domain.ABTestEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TrackABTestEvent", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// TrackABTestEvent indicates an expected call of TrackABTestEvent.
func (mr *MockEventRepositoryMockRecorder) TrackABTestEvent(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackABTestEvent", reflect.TypeOf((*MockEventRepository)(nil).TrackABTestEvent), ctx, event)
}
