apiVersion: v1
kind: Service
metadata:
  name: {{ include "inventory-service.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "inventory-service.name" . }}
    helm.sh/chart: {{ include "inventory-service.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: {{ include "inventory-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
