{{- if gt (.Values.replicaCount | int) 1 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "catalog-service.fullname" . }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "catalog-service.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
