global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'user-service'
    static_configs:
      - targets: ['host.docker.internal:51051']
  - job_name: 'catalog-service'
    static_configs:
      - targets: ['host.docker.internal:51052']
  - job_name: 'inventory-service'
    static_configs:
      - targets: ['host.docker.internal:51053']
  - job_name: 'payment-service'
    static_configs:
      - targets: ['host.docker.internal:51054']
  - job_name: 'order-service'
    static_configs:
      - targets: ['host.docker.internal:51055']
  - job_name: 'notification-service'
    static_configs:
      - targets: ['host.docker.internal:51056']
  - job_name: 'analytics-service'
    static_configs:
      - targets: ['host.docker.internal:51057']
