apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api-gateway.fullname" . }}-secrets
type: Opaque
stringData:
  JWT_SECRET: {{ required "secrets.jwtSecret is required" .Values.secrets.jwtSecret | quote }}
