// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/interfaces.go -package=mocks -destination=mocks/mock_usecase.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockNotificationUsecase is a mock of NotificationUsecase interface.
type MockNotificationUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationUsecaseMockRecorder
	isgomock struct{}
}

// MockNotificationUsecaseMockRecorder is the mock recorder for MockNotificationUsecase.
type MockNotificationUsecaseMockRecorder struct {
	mock *MockNotificationUsecase
}

// NewMockNotificationUsecase creates a new mock instance.
func NewMockNotificationUsecase(ctrl *gomock.Controller) *MockNotificationUsecase {
	mock := &MockNotificationUsecase{ctrl: ctrl}
	mock.recorder = &MockNotificationUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationUsecase) EXPECT() *MockNotificationUsecaseMockRecorder {
	return m.recorder
}

// SendEmail mocks base method.
func (m *MockNotificationUsecase) SendEmail(ctx context.Context, to, subject, body string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendEmail", ctx, to, subject, body)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendEmail indicates an expected call of SendEmail.
func (mr *MockNotificationUsecaseMockRecorder) SendEmail(ctx, to, subject, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendEmail", reflect.TypeOf((*MockNotificationUsecase)(nil).SendEmail), ctx, to, subject, body)
}
