apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: api-gateway
  namespace: marketplace-staging
spec:
  hosts:
    - api-gateway.local
  gateways:
    - api-gateway
  http:
    - route:
        - destination:
            host: api-gateway
            port:
              number: 8080
