apiVersion: v1
kind: Secret
metadata:
  name: {{ include "analytics-service.fullname" . }}-secrets
type: Opaque
stringData:
  JWT_SECRET: {{ required "secrets.jwtSecret is required" .Values.secrets.jwtSecret | quote }}
  POSTGRES_DSN: {{ required "secrets.postgresDSN is required" .Values.secrets.postgresDSN | quote }}
