apiVersion: v1
kind: Service
metadata:
  name: {{ include "analytics-service.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "analytics-service.name" . }}
    helm.sh/chart: {{ include "analytics-service.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.service.metricsPort }}"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: {{ include "analytics-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
