// Code generated by MockGen. DO NOT EDIT.
// Source: ../internal/usecase/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=../internal/usecase/interfaces.go -package=mocks -destination=mock_inventory_usecase.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/ekhodzitsky/go-ozon-marketplace/services/inventory-service/internal/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockInventoryUsecase is a mock of InventoryUsecase interface.
type MockInventoryUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockInventoryUsecaseMockRecorder
	isgomock struct{}
}

// MockInventoryUsecaseMockRecorder is the mock recorder for MockInventoryUsecase.
type MockInventoryUsecaseMockRecorder struct {
	mock *MockInventoryUsecase
}

// NewMockInventoryUsecase creates a new mock instance.
func NewMockInventoryUsecase(ctrl *gomock.Controller) *MockInventoryUsecase {
	mock := &MockInventoryUsecase{ctrl: ctrl}
	mock.recorder = &MockInventoryUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInventoryUsecase) EXPECT() *MockInventoryUsecaseMockRecorder {
	return m.recorder
}

// GetLedger mocks base method.
func (m *MockInventoryUsecase) GetLedger(ctx context.Context, productID uuid.UUID) ([]*domain.LedgerEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLedger", ctx, productID)
	ret0, _ := ret[0].([]*domain.LedgerEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLedger indicates an expected call of GetLedger.
func (mr *MockInventoryUsecaseMockRecorder) GetLedger(ctx, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLedger", reflect.TypeOf((*MockInventoryUsecase)(nil).GetLedger), ctx, productID)
}

// GetStock mocks base method.
func (m *MockInventoryUsecase) GetStock(ctx context.Context, productID uuid.UUID) (*domain.Stock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStock", ctx, productID)
	ret0, _ := ret[0].(*domain.Stock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStock indicates an expected call of GetStock.
func (mr *MockInventoryUsecaseMockRecorder) GetStock(ctx, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStock", reflect.TypeOf((*MockInventoryUsecase)(nil).GetStock), ctx, productID)
}

// Release mocks base method.
func (m *MockInventoryUsecase) Release(ctx context.Context, productID uuid.UUID, quantity int, orderID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Release", ctx, productID, quantity, orderID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Release indicates an expected call of Release.
func (mr *MockInventoryUsecaseMockRecorder) Release(ctx, productID, quantity, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockInventoryUsecase)(nil).Release), ctx, productID, quantity, orderID)
}

// Reserve mocks base method.
func (m *MockInventoryUsecase) Reserve(ctx context.Context, productID uuid.UUID, quantity int, orderID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reserve", ctx, productID, quantity, orderID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reserve indicates an expected call of Reserve.
func (mr *MockInventoryUsecaseMockRecorder) Reserve(ctx, productID, quantity, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reserve", reflect.TypeOf((*MockInventoryUsecase)(nil).Reserve), ctx, productID, quantity, orderID)
}
