// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/ekhodzitsky/go-ozon-marketplace/services/api-gateway/internal/config"
)

// Injectors from wire.go:

// InitializeApp constructs App from config.
func InitializeApp(cfg *config.Config) (*App, func(), error) {
	logger, err := provideLogger(cfg)
	if err != nil {
		return nil, nil, err
	}
	context := provideContext()
	circuitBreaker := provideCircuitBreaker()
	factory := provideClientFactory(cfg, circuitBreaker)
	client, cleanup, err := provideRedis(context, cfg)
	if err != nil {
		return nil, nil, err
	}
	engine, err := provideFeatureFlags(context, client)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	hub := provideHub(client)
	resolver, cleanup2, err := provideResolver(context, factory, engine, hub, client, cfg)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	rateLimiter := provideRateLimiter(client, cfg)
	handler := provideAdminHandler(engine, cfg)
	http := provideHTTPServer(cfg, resolver, hub, rateLimiter, handler)
	metrics := provideMetricsServer(cfg)
	app := &App{
		log:     logger,
		http:    http,
		metrics: metrics,
	}
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
