// Code generated by MockGen. DO NOT EDIT.
// Source: ../internal/usecase/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=../internal/usecase/interfaces.go -package=mocks -destination=mock_catalog_usecase.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/ekhodzitsky/go-ozon-marketplace/services/catalog-service/internal/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockCatalogUsecase is a mock of CatalogUsecase interface.
type MockCatalogUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockCatalogUsecaseMockRecorder
	isgomock struct{}
}

// MockCatalogUsecaseMockRecorder is the mock recorder for MockCatalogUsecase.
type MockCatalogUsecaseMockRecorder struct {
	mock *MockCatalogUsecase
}

// NewMockCatalogUsecase creates a new mock instance.
func NewMockCatalogUsecase(ctrl *gomock.Controller) *MockCatalogUsecase {
	mock := &MockCatalogUsecase{ctrl: ctrl}
	mock.recorder = &MockCatalogUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCatalogUsecase) EXPECT() *MockCatalogUsecaseMockRecorder {
	return m.recorder
}

// CreateProduct mocks base method.
func (m *MockCatalogUsecase) CreateProduct(ctx context.Context, name, description string, price int64, categories []string) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProduct", ctx, name, description, price, categories)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProduct indicates an expected call of CreateProduct.
func (mr *MockCatalogUsecaseMockRecorder) CreateProduct(ctx, name, description, price, categories any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProduct", reflect.TypeOf((*MockCatalogUsecase)(nil).CreateProduct), ctx, name, description, price, categories)
}

// GetProduct mocks base method.
func (m *MockCatalogUsecase) GetProduct(ctx context.Context, id uuid.UUID) (*domain.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProduct", ctx, id)
	ret0, _ := ret[0].(*domain.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProduct indicates an expected call of GetProduct.
func (mr *MockCatalogUsecaseMockRecorder) GetProduct(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProduct", reflect.TypeOf((*MockCatalogUsecase)(nil).GetProduct), ctx, id)
}

// ListProducts mocks base method.
func (m *MockCatalogUsecase) ListProducts(ctx context.Context, page, pageSize int) ([]*domain.Product, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProducts", ctx, page, pageSize)
	ret0, _ := ret[0].([]*domain.Product)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListProducts indicates an expected call of ListProducts.
func (mr *MockCatalogUsecaseMockRecorder) ListProducts(ctx, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProducts", reflect.TypeOf((*MockCatalogUsecase)(nil).ListProducts), ctx, page, pageSize)
}

// SearchProducts mocks base method.
func (m *MockCatalogUsecase) SearchProducts(ctx context.Context, query string, page, pageSize int) ([]*domain.Product, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchProducts", ctx, query, page, pageSize)
	ret0, _ := ret[0].([]*domain.Product)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SearchProducts indicates an expected call of SearchProducts.
func (mr *MockCatalogUsecaseMockRecorder) SearchProducts(ctx, query, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchProducts", reflect.TypeOf((*MockCatalogUsecase)(nil).SearchProducts), ctx, query, page, pageSize)
}
