// Code generated by MockGen. DO NOT EDIT.
// Source: ../internal/repository/repository.go
//
// Generated by this command:
//
//	mockgen -source=../internal/repository/repository.go -package=mocks -destination=mock_catalog_repository.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/ekhodzitsky/go-ozon-marketplace/services/catalog-service/internal/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockProductRepository is a mock of ProductRepository interface.
type MockProductRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProductRepositoryMockRecorder
	isgomock struct{}
}

// MockProductRepositoryMockRecorder is the mock recorder for MockProductRepository.
type MockProductRepositoryMockRecorder struct {
	mock *MockProductRepository
}

// NewMockProductRepository creates a new mock instance.
func NewMockProductRepository(ctrl *gomock.Controller) *MockProductRepository {
	mock := &MockProductRepository{ctrl: ctrl}
	mock.recorder = &MockProductRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductRepository) EXPECT() *MockProductRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockProductRepository) Create(ctx context.Context, product *domain.Product) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, product)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockProductRepositoryMockRecorder) Create(ctx, product any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockProductRepository)(nil).Create), ctx, product)
}

// GetByID mocks base method.
func (m *MockProductRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockProductRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockProductRepository)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockProductRepository) List(ctx context.Context, page, pageSize int) ([]*domain.Product, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, page, pageSize)
	ret0, _ := ret[0].([]*domain.Product)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockProductRepositoryMockRecorder) List(ctx, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockProductRepository)(nil).List), ctx, page, pageSize)
}

// MockProductSearchRepository is a mock of ProductSearchRepository interface.
type MockProductSearchRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProductSearchRepositoryMockRecorder
	isgomock struct{}
}

// MockProductSearchRepositoryMockRecorder is the mock recorder for MockProductSearchRepository.
type MockProductSearchRepositoryMockRecorder struct {
	mock *MockProductSearchRepository
}

// NewMockProductSearchRepository creates a new mock instance.
func NewMockProductSearchRepository(ctrl *gomock.Controller) *MockProductSearchRepository {
	mock := &MockProductSearchRepository{ctrl: ctrl}
	mock.recorder = &MockProductSearchRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductSearchRepository) EXPECT() *MockProductSearchRepositoryMockRecorder {
	return m.recorder
}

// Index mocks base method.
func (m *MockProductSearchRepository) Index(ctx context.Context, product *domain.Product) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Index", ctx, product)
	ret0, _ := ret[0].(error)
	return ret0
}

// Index indicates an expected call of Index.
func (mr *MockProductSearchRepositoryMockRecorder) Index(ctx, product any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Index", reflect.TypeOf((*MockProductSearchRepository)(nil).Index), ctx, product)
}

// Search mocks base method.
func (m *MockProductSearchRepository) Search(ctx context.Context, query string, page, pageSize int) ([]*domain.Product, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, query, page, pageSize)
	ret0, _ := ret[0].([]*domain.Product)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Search indicates an expected call of Search.
func (mr *MockProductSearchRepositoryMockRecorder) Search(ctx, query, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockProductSearchRepository)(nil).Search), ctx, query, page, pageSize)
}

// MockOutboxRepository is a mock of OutboxRepository interface.
type MockOutboxRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOutboxRepositoryMockRecorder
	isgomock struct{}
}

// MockOutboxRepositoryMockRecorder is the mock recorder for MockOutboxRepository.
type MockOutboxRepositoryMockRecorder struct {
	mock *MockOutboxRepository
}

// NewMockOutboxRepository creates a new mock instance.
func NewMockOutboxRepository(ctrl *gomock.Controller) *MockOutboxRepository {
	mock := &MockOutboxRepository{ctrl: ctrl}
	mock.recorder = &MockOutboxRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOutboxRepository) EXPECT() *MockOutboxRepositoryMockRecorder {
	return m.recorder
}

// BatchMarkProcessed mocks base method.
func (m *MockOutboxRepository) BatchMarkProcessed(ctx context.Context, ids []uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchMarkProcessed", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchMarkProcessed indicates an expected call of BatchMarkProcessed.
func (mr *MockOutboxRepositoryMockRecorder) BatchMarkProcessed(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchMarkProcessed", reflect.TypeOf((*MockOutboxRepository)(nil).BatchMarkProcessed), ctx, ids)
}

// Create mocks base method.
func (m *MockOutboxRepository) Create(ctx context.Context, event *domain.OutboxEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockOutboxRepositoryMockRecorder) Create(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOutboxRepository)(nil).Create), ctx, event)
}

// GetUnprocessed mocks base method.
func (m *MockOutboxRepository) GetUnprocessed(ctx context.Context, limit int) ([]domain.OutboxEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUnprocessed", ctx, limit)
	ret0, _ := ret[0].([]domain.OutboxEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUnprocessed indicates an expected call of GetUnprocessed.
func (mr *MockOutboxRepositoryMockRecorder) GetUnprocessed(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUnprocessed", reflect.TypeOf((*MockOutboxRepository)(nil).GetUnprocessed), ctx, limit)
}

// MarkProcessed mocks base method.
func (m *MockOutboxRepository) MarkProcessed(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkProcessed", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkProcessed indicates an expected call of MarkProcessed.
func (mr *MockOutboxRepositoryMockRecorder) MarkProcessed(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkProcessed", reflect.TypeOf((*MockOutboxRepository)(nil).MarkProcessed), ctx, id)
}
