replicaCount: 2

image:
  repository: go-ozon-marketplace/user-service
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  grpcPort: 50051
  httpPort: 8080
  metricsPort: 51051

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
  hosts:
    - host: user-service.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

env:
  GRPC_PORT: "50051"
  HTTP_PORT: "8080"
  POSTGRES_DSN: "postgres://ozon:ozonpass@postgres:5432/marketplace?sslmode=disable"
  JWT_SECRET: "super-secret-key"

nodeSelector: {}
tolerations: []
affinity: {}
