// Code generated by MockGen. DO NOT EDIT.
// Source: ../internal/usecase/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=../internal/usecase/interfaces.go -package=mocks -destination=mock_usecase.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/ekhodzitsky/go-ozon-marketplace/services/payment-service/internal/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockPaymentUsecase is a mock of PaymentUsecase interface.
type MockPaymentUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentUsecaseMockRecorder
	isgomock struct{}
}

// MockPaymentUsecaseMockRecorder is the mock recorder for MockPaymentUsecase.
type MockPaymentUsecaseMockRecorder struct {
	mock *MockPaymentUsecase
}

// NewMockPaymentUsecase creates a new mock instance.
func NewMockPaymentUsecase(ctrl *gomock.Controller) *MockPaymentUsecase {
	mock := &MockPaymentUsecase{ctrl: ctrl}
	mock.recorder = &MockPaymentUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentUsecase) EXPECT() *MockPaymentUsecaseMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockPaymentUsecase) GetByID(ctx context.Context, paymentID uuid.UUID) (*domain.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, paymentID)
	ret0, _ := ret[0].(*domain.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockPaymentUsecaseMockRecorder) GetByID(ctx, paymentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockPaymentUsecase)(nil).GetByID), ctx, paymentID)
}

// GetRefund mocks base method.
func (m *MockPaymentUsecase) GetRefund(ctx context.Context, refundID uuid.UUID) (*domain.Refund, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRefund", ctx, refundID)
	ret0, _ := ret[0].(*domain.Refund)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRefund indicates an expected call of GetRefund.
func (mr *MockPaymentUsecaseMockRecorder) GetRefund(ctx, refundID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRefund", reflect.TypeOf((*MockPaymentUsecase)(nil).GetRefund), ctx, refundID)
}

// ListRefunds mocks base method.
func (m *MockPaymentUsecase) ListRefunds(ctx context.Context, paymentID uuid.UUID) ([]*domain.Refund, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRefunds", ctx, paymentID)
	ret0, _ := ret[0].([]*domain.Refund)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRefunds indicates an expected call of ListRefunds.
func (mr *MockPaymentUsecaseMockRecorder) ListRefunds(ctx, paymentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRefunds", reflect.TypeOf((*MockPaymentUsecase)(nil).ListRefunds), ctx, paymentID)
}

// ProcessPayment mocks base method.
func (m *MockPaymentUsecase) ProcessPayment(ctx context.Context, orderID, userID uuid.UUID, amountCents int64) (*domain.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessPayment", ctx, orderID, userID, amountCents)
	ret0, _ := ret[0].(*domain.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessPayment indicates an expected call of ProcessPayment.
func (mr *MockPaymentUsecaseMockRecorder) ProcessPayment(ctx, orderID, userID, amountCents any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessPayment", reflect.TypeOf((*MockPaymentUsecase)(nil).ProcessPayment), ctx, orderID, userID, amountCents)
}

// Refund mocks base method.
func (m *MockPaymentUsecase) Refund(ctx context.Context, paymentID uuid.UUID, idempotencyKey string) (*domain.Payment, *domain.Refund, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refund", ctx, paymentID, idempotencyKey)
	ret0, _ := ret[0].(*domain.Payment)
	ret1, _ := ret[1].(*domain.Refund)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Refund indicates an expected call of Refund.
func (mr *MockPaymentUsecaseMockRecorder) Refund(ctx, paymentID, idempotencyKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refund", reflect.TypeOf((*MockPaymentUsecase)(nil).Refund), ctx, paymentID, idempotencyKey)
}
