replicaCount: 2

image:
  repository: go-ozon-marketplace/analytics-service
  pullPolicy: IfNotPresent
  tag: ""

service:
  type: ClusterIP
  grpcPort: 50057
  metricsPort: 51057

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
  hosts:
    - host: analytics-service.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

env:
  GRPC_PORT: "50057"
  CLICKHOUSE_DSN: "clickhouse:9000"
  KAFKA_BROKERS: "kafka:9092"
  KAFKA_TOPICS: "order-events"
  KAFKA_CONSUMER_GROUP: "analytics-service"

secrets:
  jwtSecret: ""      # обязательно

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}
