// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Product struct {
	ID          string   `json:"id"`
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Price       float64  `json:"price"`
	Stock       int32    `json:"stock"`
	Categories  []string `json:"categories"`
	CreatedAt   string   `json:"createdAt"`
}

type ProductConnection struct {
	Products []*Product `json:"products"`
	Total    int32      `json:"total"`
}

type Query struct {
}

type User struct {
	ID        string `json:"id"`
	Email     string `json:"email"`
	Name      string `json:"name"`
	CreatedAt string `json:"createdAt"`
}
