// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ABTestAssignment struct {
	Experiment string `json:"experiment"`
	Variation  string `json:"variation"`
}

type FeatureFlags struct {
	NewCheckoutFlow bool `json:"newCheckoutFlow"`
	FastSearch      bool `json:"fastSearch"`
	DiscountSystem  bool `json:"discountSystem"`
	RealTimeUpdates bool `json:"realTimeUpdates"`
}

type Inventory struct {
	ProductID string `json:"productId"`
	Available int32  `json:"available"`
	Reserved  int32  `json:"reserved"`
}

type Mutation struct {
}

type Order struct {
	ID          string       `json:"id"`
	UserID      string       `json:"userId"`
	Items       []*OrderItem `json:"items"`
	TotalAmount float64      `json:"totalAmount"`
	Status      string       `json:"status"`
	CreatedAt   string       `json:"createdAt"`
	UpdatedAt   string       `json:"updatedAt"`
}

type OrderConnection struct {
	Orders []*Order `json:"orders"`
	Total  int32    `json:"total"`
}

type OrderItem struct {
	ProductID string  `json:"productId"`
	Quantity  int32   `json:"quantity"`
	Price     float64 `json:"price"`
}

type OrderItemInput struct {
	ProductID string  `json:"productId"`
	Quantity  int32   `json:"quantity"`
	Price     float64 `json:"price"`
}

type Product struct {
	ID          string   `json:"id"`
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Price       float64  `json:"price"`
	Categories  []string `json:"categories"`
	CreatedAt   string   `json:"createdAt"`
}

type ProductConnection struct {
	Products []*Product `json:"products"`
	Total    int32      `json:"total"`
}

type Query struct {
}

type Subscription struct {
}

type User struct {
	ID        string `json:"id"`
	Email     string `json:"email"`
	Name      string `json:"name"`
	CreatedAt string `json:"createdAt"`
}
