// Code generated by MockGen. DO NOT EDIT.
// Source: ../internal/saga/statemachine/statemachine.go
//
// Generated by this command:
//
//	mockgen -source=../internal/saga/statemachine/statemachine.go -package=mocks -destination=mock_saga_statemachine.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	domain "github.com/ekhodzitsky/go-ozon-marketplace/services/order-service/internal/domain"
	steps "github.com/ekhodzitsky/go-ozon-marketplace/services/order-service/internal/saga/steps"
	gomock "go.uber.org/mock/gomock"
)

// MockStateMachine is a mock of StateMachine interface.
type MockStateMachine struct {
	ctrl     *gomock.Controller
	recorder *MockStateMachineMockRecorder
	isgomock struct{}
}

// MockStateMachineMockRecorder is the mock recorder for MockStateMachine.
type MockStateMachineMockRecorder struct {
	mock *MockStateMachine
}

// NewMockStateMachine creates a new mock instance.
func NewMockStateMachine(ctrl *gomock.Controller) *MockStateMachine {
	mock := &MockStateMachine{ctrl: ctrl}
	mock.recorder = &MockStateMachineMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStateMachine) EXPECT() *MockStateMachineMockRecorder {
	return m.recorder
}

// IsTerminal mocks base method.
func (m *MockStateMachine) IsTerminal(saga *domain.Saga) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsTerminal", saga)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsTerminal indicates an expected call of IsTerminal.
func (mr *MockStateMachineMockRecorder) IsTerminal(saga any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsTerminal", reflect.TypeOf((*MockStateMachine)(nil).IsTerminal), saga)
}

// Next mocks base method.
func (m *MockStateMachine) Next(saga *domain.Saga, order *domain.Order) (steps.Step, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Next", saga, order)
	ret0, _ := ret[0].(steps.Step)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Next indicates an expected call of Next.
func (mr *MockStateMachineMockRecorder) Next(saga, order any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Next", reflect.TypeOf((*MockStateMachine)(nil).Next), saga, order)
}
