// Code generated by MockGen. DO NOT EDIT.
// Source: ../internal/infrastructure/grpcclient/catalog.go
//
// Generated by this command:
//
//	mockgen -source=../internal/infrastructure/grpcclient/catalog.go -package=mocks -destination=mock_catalog_client.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	catalogv1 "github.com/ekhodzitsky/go-ozon-marketplace/api/gen/go/catalog/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockCatalogClient is a mock of CatalogClient interface.
type MockCatalogClient struct {
	ctrl     *gomock.Controller
	recorder *MockCatalogClientMockRecorder
	isgomock struct{}
}

// MockCatalogClientMockRecorder is the mock recorder for MockCatalogClient.
type MockCatalogClientMockRecorder struct {
	mock *MockCatalogClient
}

// NewMockCatalogClient creates a new mock instance.
func NewMockCatalogClient(ctrl *gomock.Controller) *MockCatalogClient {
	mock := &MockCatalogClient{ctrl: ctrl}
	mock.recorder = &MockCatalogClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCatalogClient) EXPECT() *MockCatalogClientMockRecorder {
	return m.recorder
}

// GetProduct mocks base method.
func (m *MockCatalogClient) GetProduct(ctx context.Context, productID string) (*catalogv1.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProduct", ctx, productID)
	ret0, _ := ret[0].(*catalogv1.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProduct indicates an expected call of GetProduct.
func (mr *MockCatalogClientMockRecorder) GetProduct(ctx, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProduct", reflect.TypeOf((*MockCatalogClient)(nil).GetProduct), ctx, productID)
}
