// Code generated by MockGen. DO NOT EDIT.
// Source: ../internal/saga/executor/executor.go
//
// Generated by this command:
//
//	mockgen -source=../internal/saga/executor/executor.go -package=mocks -destination=mock_saga_executor.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/ekhodzitsky/go-ozon-marketplace/services/order-service/internal/domain"
	steps "github.com/ekhodzitsky/go-ozon-marketplace/services/order-service/internal/saga/steps"
	gomock "go.uber.org/mock/gomock"
)

// MockStepExecutor is a mock of StepExecutor interface.
type MockStepExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockStepExecutorMockRecorder
	isgomock struct{}
}

// MockStepExecutorMockRecorder is the mock recorder for MockStepExecutor.
type MockStepExecutorMockRecorder struct {
	mock *MockStepExecutor
}

// NewMockStepExecutor creates a new mock instance.
func NewMockStepExecutor(ctrl *gomock.Controller) *MockStepExecutor {
	mock := &MockStepExecutor{ctrl: ctrl}
	mock.recorder = &MockStepExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStepExecutor) EXPECT() *MockStepExecutorMockRecorder {
	return m.recorder
}

// Compensate mocks base method.
func (m *MockStepExecutor) Compensate(ctx context.Context, step steps.Step, saga *domain.Saga, order *domain.Order, idempotencyKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Compensate", ctx, step, saga, order, idempotencyKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// Compensate indicates an expected call of Compensate.
func (mr *MockStepExecutorMockRecorder) Compensate(ctx, step, saga, order, idempotencyKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Compensate", reflect.TypeOf((*MockStepExecutor)(nil).Compensate), ctx, step, saga, order, idempotencyKey)
}

// Execute mocks base method.
func (m *MockStepExecutor) Execute(ctx context.Context, step steps.Step, saga *domain.Saga, order *domain.Order, idempotencyKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, step, saga, order, idempotencyKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockStepExecutorMockRecorder) Execute(ctx, step, saga, order, idempotencyKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockStepExecutor)(nil).Execute), ctx, step, saga, order, idempotencyKey)
}
