// Code generated by MockGen. DO NOT EDIT.
// Source: ../internal/repository/repository.go
//
// Generated by this command:
//
//	mockgen -source=../internal/repository/repository.go -package=mocks -destination=mock_order_repository.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/ekhodzitsky/go-ozon-marketplace/services/order-service/internal/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockOrderRepository is a mock of OrderRepository interface.
type MockOrderRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOrderRepositoryMockRecorder
	isgomock struct{}
}

// MockOrderRepositoryMockRecorder is the mock recorder for MockOrderRepository.
type MockOrderRepositoryMockRecorder struct {
	mock *MockOrderRepository
}

// NewMockOrderRepository creates a new mock instance.
func NewMockOrderRepository(ctrl *gomock.Controller) *MockOrderRepository {
	mock := &MockOrderRepository{ctrl: ctrl}
	mock.recorder = &MockOrderRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderRepository) EXPECT() *MockOrderRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockOrderRepository) Create(ctx context.Context, order *domain.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, order)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockOrderRepositoryMockRecorder) Create(ctx, order any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOrderRepository)(nil).Create), ctx, order)
}

// GetByID mocks base method.
func (m *MockOrderRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockOrderRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockOrderRepository)(nil).GetByID), ctx, id)
}

// ListByUser mocks base method.
func (m *MockOrderRepository) ListByUser(ctx context.Context, userID uuid.UUID, page, pageSize int) ([]domain.Order, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", ctx, userID, page, pageSize)
	ret0, _ := ret[0].([]domain.Order)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockOrderRepositoryMockRecorder) ListByUser(ctx, userID, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockOrderRepository)(nil).ListByUser), ctx, userID, page, pageSize)
}

// UpdateStatus mocks base method.
func (m *MockOrderRepository) UpdateStatus(ctx context.Context, id uuid.UUID, status domain.OrderStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockOrderRepositoryMockRecorder) UpdateStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockOrderRepository)(nil).UpdateStatus), ctx, id, status)
}

// MockOutboxRepository is a mock of OutboxRepository interface.
type MockOutboxRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOutboxRepositoryMockRecorder
	isgomock struct{}
}

// MockOutboxRepositoryMockRecorder is the mock recorder for MockOutboxRepository.
type MockOutboxRepositoryMockRecorder struct {
	mock *MockOutboxRepository
}

// NewMockOutboxRepository creates a new mock instance.
func NewMockOutboxRepository(ctrl *gomock.Controller) *MockOutboxRepository {
	mock := &MockOutboxRepository{ctrl: ctrl}
	mock.recorder = &MockOutboxRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOutboxRepository) EXPECT() *MockOutboxRepositoryMockRecorder {
	return m.recorder
}

// BatchMarkProcessed mocks base method.
func (m *MockOutboxRepository) BatchMarkProcessed(ctx context.Context, ids []uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchMarkProcessed", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchMarkProcessed indicates an expected call of BatchMarkProcessed.
func (mr *MockOutboxRepositoryMockRecorder) BatchMarkProcessed(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchMarkProcessed", reflect.TypeOf((*MockOutboxRepository)(nil).BatchMarkProcessed), ctx, ids)
}

// Begin mocks base method.
func (m *MockOutboxRepository) Begin(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Begin", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Begin indicates an expected call of Begin.
func (mr *MockOutboxRepositoryMockRecorder) Begin(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Begin", reflect.TypeOf((*MockOutboxRepository)(nil).Begin), ctx)
}

// Commit mocks base method.
func (m *MockOutboxRepository) Commit(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Commit indicates an expected call of Commit.
func (mr *MockOutboxRepositoryMockRecorder) Commit(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockOutboxRepository)(nil).Commit), ctx)
}

// Create mocks base method.
func (m *MockOutboxRepository) Create(ctx context.Context, event *domain.OutboxEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockOutboxRepositoryMockRecorder) Create(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOutboxRepository)(nil).Create), ctx, event)
}

// GetUnprocessed mocks base method.
func (m *MockOutboxRepository) GetUnprocessed(ctx context.Context, limit int) ([]domain.OutboxEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUnprocessed", ctx, limit)
	ret0, _ := ret[0].([]domain.OutboxEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUnprocessed indicates an expected call of GetUnprocessed.
func (mr *MockOutboxRepositoryMockRecorder) GetUnprocessed(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUnprocessed", reflect.TypeOf((*MockOutboxRepository)(nil).GetUnprocessed), ctx, limit)
}

// IncrementRetryAndSetError mocks base method.
func (m *MockOutboxRepository) IncrementRetryAndSetError(ctx context.Context, id uuid.UUID, lastError string, nextRetryAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementRetryAndSetError", ctx, id, lastError, nextRetryAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementRetryAndSetError indicates an expected call of IncrementRetryAndSetError.
func (mr *MockOutboxRepositoryMockRecorder) IncrementRetryAndSetError(ctx, id, lastError, nextRetryAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementRetryAndSetError", reflect.TypeOf((*MockOutboxRepository)(nil).IncrementRetryAndSetError), ctx, id, lastError, nextRetryAt)
}

// MarkProcessed mocks base method.
func (m *MockOutboxRepository) MarkProcessed(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkProcessed", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkProcessed indicates an expected call of MarkProcessed.
func (mr *MockOutboxRepositoryMockRecorder) MarkProcessed(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkProcessed", reflect.TypeOf((*MockOutboxRepository)(nil).MarkProcessed), ctx, id)
}

// MoveToDLQ mocks base method.
func (m *MockOutboxRepository) MoveToDLQ(ctx context.Context, event *domain.OutboxEvent, failedAt time.Time, lastError string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MoveToDLQ", ctx, event, failedAt, lastError)
	ret0, _ := ret[0].(error)
	return ret0
}

// MoveToDLQ indicates an expected call of MoveToDLQ.
func (mr *MockOutboxRepositoryMockRecorder) MoveToDLQ(ctx, event, failedAt, lastError any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveToDLQ", reflect.TypeOf((*MockOutboxRepository)(nil).MoveToDLQ), ctx, event, failedAt, lastError)
}

// Rollback mocks base method.
func (m *MockOutboxRepository) Rollback(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rollback", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Rollback indicates an expected call of Rollback.
func (mr *MockOutboxRepositoryMockRecorder) Rollback(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rollback", reflect.TypeOf((*MockOutboxRepository)(nil).Rollback), ctx)
}

// MockSagaRepository is a mock of SagaRepository interface.
type MockSagaRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSagaRepositoryMockRecorder
	isgomock struct{}
}

// MockSagaRepositoryMockRecorder is the mock recorder for MockSagaRepository.
type MockSagaRepositoryMockRecorder struct {
	mock *MockSagaRepository
}

// NewMockSagaRepository creates a new mock instance.
func NewMockSagaRepository(ctrl *gomock.Controller) *MockSagaRepository {
	mock := &MockSagaRepository{ctrl: ctrl}
	mock.recorder = &MockSagaRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSagaRepository) EXPECT() *MockSagaRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSagaRepository) Create(ctx context.Context, saga *domain.Saga) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, saga)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSagaRepositoryMockRecorder) Create(ctx, saga any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSagaRepository)(nil).Create), ctx, saga)
}

// GetByOrderID mocks base method.
func (m *MockSagaRepository) GetByOrderID(ctx context.Context, orderID uuid.UUID) (*domain.Saga, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByOrderID", ctx, orderID)
	ret0, _ := ret[0].(*domain.Saga)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByOrderID indicates an expected call of GetByOrderID.
func (mr *MockSagaRepositoryMockRecorder) GetByOrderID(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByOrderID", reflect.TypeOf((*MockSagaRepository)(nil).GetByOrderID), ctx, orderID)
}

// ListIncomplete mocks base method.
func (m *MockSagaRepository) ListIncomplete(ctx context.Context, limit int) ([]domain.Saga, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListIncomplete", ctx, limit)
	ret0, _ := ret[0].([]domain.Saga)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListIncomplete indicates an expected call of ListIncomplete.
func (mr *MockSagaRepositoryMockRecorder) ListIncomplete(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListIncomplete", reflect.TypeOf((*MockSagaRepository)(nil).ListIncomplete), ctx, limit)
}

// Save mocks base method.
func (m *MockSagaRepository) Save(ctx context.Context, saga *domain.Saga) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, saga)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockSagaRepositoryMockRecorder) Save(ctx, saga any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockSagaRepository)(nil).Save), ctx, saga)
}

// UpdateStatus mocks base method.
func (m *MockSagaRepository) UpdateStatus(ctx context.Context, orderID uuid.UUID, status domain.SagaStatus, step, errMsg string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, orderID, status, step, errMsg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockSagaRepositoryMockRecorder) UpdateStatus(ctx, orderID, status, step, errMsg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockSagaRepository)(nil).UpdateStatus), ctx, orderID, status, step, errMsg)
}
