// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ekhodzitsky/go-ozon-marketplace/api/gen/go/payment/v1 (interfaces: PaymentServiceClient)
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=mock_payment_service_client.go github.com/ekhodzitsky/go-ozon-marketplace/api/gen/go/payment/v1 PaymentServiceClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	paymentv1 "github.com/ekhodzitsky/go-ozon-marketplace/api/gen/go/payment/v1"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockPaymentServiceClient is a mock of PaymentServiceClient interface.
type MockPaymentServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentServiceClientMockRecorder
	isgomock struct{}
}

// MockPaymentServiceClientMockRecorder is the mock recorder for MockPaymentServiceClient.
type MockPaymentServiceClientMockRecorder struct {
	mock *MockPaymentServiceClient
}

// NewMockPaymentServiceClient creates a new mock instance.
func NewMockPaymentServiceClient(ctrl *gomock.Controller) *MockPaymentServiceClient {
	mock := &MockPaymentServiceClient{ctrl: ctrl}
	mock.recorder = &MockPaymentServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentServiceClient) EXPECT() *MockPaymentServiceClientMockRecorder {
	return m.recorder
}

// GetRefund mocks base method.
func (m *MockPaymentServiceClient) GetRefund(ctx context.Context, in *paymentv1.GetRefundRequest, opts ...grpc.CallOption) (*paymentv1.GetRefundResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetRefund", varargs...)
	ret0, _ := ret[0].(*paymentv1.GetRefundResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRefund indicates an expected call of GetRefund.
func (mr *MockPaymentServiceClientMockRecorder) GetRefund(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRefund", reflect.TypeOf((*MockPaymentServiceClient)(nil).GetRefund), varargs...)
}

// ListRefunds mocks base method.
func (m *MockPaymentServiceClient) ListRefunds(ctx context.Context, in *paymentv1.ListRefundsRequest, opts ...grpc.CallOption) (*paymentv1.ListRefundsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListRefunds", varargs...)
	ret0, _ := ret[0].(*paymentv1.ListRefundsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRefunds indicates an expected call of ListRefunds.
func (mr *MockPaymentServiceClientMockRecorder) ListRefunds(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRefunds", reflect.TypeOf((*MockPaymentServiceClient)(nil).ListRefunds), varargs...)
}

// ProcessPayment mocks base method.
func (m *MockPaymentServiceClient) ProcessPayment(ctx context.Context, in *paymentv1.ProcessPaymentRequest, opts ...grpc.CallOption) (*paymentv1.ProcessPaymentResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ProcessPayment", varargs...)
	ret0, _ := ret[0].(*paymentv1.ProcessPaymentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessPayment indicates an expected call of ProcessPayment.
func (mr *MockPaymentServiceClientMockRecorder) ProcessPayment(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessPayment", reflect.TypeOf((*MockPaymentServiceClient)(nil).ProcessPayment), varargs...)
}

// Refund mocks base method.
func (m *MockPaymentServiceClient) Refund(ctx context.Context, in *paymentv1.RefundRequest, opts ...grpc.CallOption) (*paymentv1.RefundResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Refund", varargs...)
	ret0, _ := ret[0].(*paymentv1.RefundResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Refund indicates an expected call of Refund.
func (mr *MockPaymentServiceClientMockRecorder) Refund(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refund", reflect.TypeOf((*MockPaymentServiceClient)(nil).Refund), varargs...)
}
