// Code generated by MockGen. DO NOT EDIT.
// Source: ../internal/saga/domain.go
//
// Generated by this command:
//
//	mockgen -source=../internal/saga/domain.go -package=mocks -destination=mock_saga_repository.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	saga "github.com/ekhodzitsky/go-ozon-marketplace/services/order-service/internal/saga"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockLocker is a mock of Locker interface.
type MockLocker struct {
	ctrl     *gomock.Controller
	recorder *MockLockerMockRecorder
	isgomock struct{}
}

// MockLockerMockRecorder is the mock recorder for MockLocker.
type MockLockerMockRecorder struct {
	mock *MockLocker
}

// NewMockLocker creates a new mock instance.
func NewMockLocker(ctrl *gomock.Controller) *MockLocker {
	mock := &MockLocker{ctrl: ctrl}
	mock.recorder = &MockLockerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLocker) EXPECT() *MockLockerMockRecorder {
	return m.recorder
}

// TryLock mocks base method.
func (m *MockLocker) TryLock(ctx context.Context, key string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TryLock", ctx, key)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TryLock indicates an expected call of TryLock.
func (mr *MockLockerMockRecorder) TryLock(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TryLock", reflect.TypeOf((*MockLocker)(nil).TryLock), ctx, key)
}

// Unlock mocks base method.
func (m *MockLocker) Unlock(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unlock", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unlock indicates an expected call of Unlock.
func (mr *MockLockerMockRecorder) Unlock(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unlock", reflect.TypeOf((*MockLocker)(nil).Unlock), ctx, key)
}

// MockRecoverer is a mock of Recoverer interface.
type MockRecoverer struct {
	ctrl     *gomock.Controller
	recorder *MockRecovererMockRecorder
	isgomock struct{}
}

// MockRecovererMockRecorder is the mock recorder for MockRecoverer.
type MockRecovererMockRecorder struct {
	mock *MockRecoverer
}

// NewMockRecoverer creates a new mock instance.
func NewMockRecoverer(ctrl *gomock.Controller) *MockRecoverer {
	mock := &MockRecoverer{ctrl: ctrl}
	mock.recorder = &MockRecovererMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecoverer) EXPECT() *MockRecovererMockRecorder {
	return m.recorder
}

// Recover mocks base method.
func (m *MockRecoverer) Recover(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recover", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Recover indicates an expected call of Recover.
func (mr *MockRecovererMockRecorder) Recover(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recover", reflect.TypeOf((*MockRecoverer)(nil).Recover), ctx)
}

// MockSagaRepository is a mock of SagaRepository interface.
type MockSagaRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSagaRepositoryMockRecorder
	isgomock struct{}
}

// MockSagaRepositoryMockRecorder is the mock recorder for MockSagaRepository.
type MockSagaRepositoryMockRecorder struct {
	mock *MockSagaRepository
}

// NewMockSagaRepository creates a new mock instance.
func NewMockSagaRepository(ctrl *gomock.Controller) *MockSagaRepository {
	mock := &MockSagaRepository{ctrl: ctrl}
	mock.recorder = &MockSagaRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSagaRepository) EXPECT() *MockSagaRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSagaRepository) Create(ctx context.Context, s *saga.Saga) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSagaRepositoryMockRecorder) Create(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSagaRepository)(nil).Create), ctx, s)
}

// GetByOrderID mocks base method.
func (m *MockSagaRepository) GetByOrderID(ctx context.Context, orderID uuid.UUID) (*saga.Saga, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByOrderID", ctx, orderID)
	ret0, _ := ret[0].(*saga.Saga)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByOrderID indicates an expected call of GetByOrderID.
func (mr *MockSagaRepositoryMockRecorder) GetByOrderID(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByOrderID", reflect.TypeOf((*MockSagaRepository)(nil).GetByOrderID), ctx, orderID)
}

// ListIncomplete mocks base method.
func (m *MockSagaRepository) ListIncomplete(ctx context.Context, limit int) ([]saga.Saga, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListIncomplete", ctx, limit)
	ret0, _ := ret[0].([]saga.Saga)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListIncomplete indicates an expected call of ListIncomplete.
func (mr *MockSagaRepositoryMockRecorder) ListIncomplete(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListIncomplete", reflect.TypeOf((*MockSagaRepository)(nil).ListIncomplete), ctx, limit)
}

// Save mocks base method.
func (m *MockSagaRepository) Save(ctx context.Context, s *saga.Saga) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockSagaRepositoryMockRecorder) Save(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockSagaRepository)(nil).Save), ctx, s)
}

// UpdateStatus mocks base method.
func (m *MockSagaRepository) UpdateStatus(ctx context.Context, orderID uuid.UUID, status saga.SagaStatus, step, errMsg string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, orderID, status, step, errMsg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockSagaRepositoryMockRecorder) UpdateStatus(ctx, orderID, status, step, errMsg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockSagaRepository)(nil).UpdateStatus), ctx, orderID, status, step, errMsg)
}
