// Code generated by MockGen. DO NOT EDIT.
// Source: ../internal/saga/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=../internal/saga/interfaces.go -package=mocks -destination=mock_saga_clients.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockInventoryClient is a mock of InventoryClient interface.
type MockInventoryClient struct {
	ctrl     *gomock.Controller
	recorder *MockInventoryClientMockRecorder
	isgomock struct{}
}

// MockInventoryClientMockRecorder is the mock recorder for MockInventoryClient.
type MockInventoryClientMockRecorder struct {
	mock *MockInventoryClient
}

// NewMockInventoryClient creates a new mock instance.
func NewMockInventoryClient(ctrl *gomock.Controller) *MockInventoryClient {
	mock := &MockInventoryClient{ctrl: ctrl}
	mock.recorder = &MockInventoryClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInventoryClient) EXPECT() *MockInventoryClientMockRecorder {
	return m.recorder
}

// Release mocks base method.
func (m *MockInventoryClient) Release(ctx context.Context, productID string, quantity int32, orderID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Release", ctx, productID, quantity, orderID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Release indicates an expected call of Release.
func (mr *MockInventoryClientMockRecorder) Release(ctx, productID, quantity, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockInventoryClient)(nil).Release), ctx, productID, quantity, orderID)
}

// Reserve mocks base method.
func (m *MockInventoryClient) Reserve(ctx context.Context, productID string, quantity int32, orderID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reserve", ctx, productID, quantity, orderID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reserve indicates an expected call of Reserve.
func (mr *MockInventoryClientMockRecorder) Reserve(ctx, productID, quantity, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reserve", reflect.TypeOf((*MockInventoryClient)(nil).Reserve), ctx, productID, quantity, orderID)
}

// MockPaymentClient is a mock of PaymentClient interface.
type MockPaymentClient struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentClientMockRecorder
	isgomock struct{}
}

// MockPaymentClientMockRecorder is the mock recorder for MockPaymentClient.
type MockPaymentClientMockRecorder struct {
	mock *MockPaymentClient
}

// NewMockPaymentClient creates a new mock instance.
func NewMockPaymentClient(ctrl *gomock.Controller) *MockPaymentClient {
	mock := &MockPaymentClient{ctrl: ctrl}
	mock.recorder = &MockPaymentClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentClient) EXPECT() *MockPaymentClientMockRecorder {
	return m.recorder
}

// ProcessPayment mocks base method.
func (m *MockPaymentClient) ProcessPayment(ctx context.Context, orderID, userID string, amount int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessPayment", ctx, orderID, userID, amount)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessPayment indicates an expected call of ProcessPayment.
func (mr *MockPaymentClientMockRecorder) ProcessPayment(ctx, orderID, userID, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessPayment", reflect.TypeOf((*MockPaymentClient)(nil).ProcessPayment), ctx, orderID, userID, amount)
}

// Refund mocks base method.
func (m *MockPaymentClient) Refund(ctx context.Context, paymentID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refund", ctx, paymentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Refund indicates an expected call of Refund.
func (mr *MockPaymentClientMockRecorder) Refund(ctx, paymentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refund", reflect.TypeOf((*MockPaymentClient)(nil).Refund), ctx, paymentID)
}
