// Code generated by MockGen. DO NOT EDIT.
// Source: ../internal/saga/steps/step.go
//
// Generated by this command:
//
//	mockgen -source=../internal/saga/steps/step.go -package=mocks -destination=mock_saga_step.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/ekhodzitsky/go-ozon-marketplace/services/order-service/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockStep is a mock of Step interface.
type MockStep struct {
	ctrl     *gomock.Controller
	recorder *MockStepMockRecorder
	isgomock struct{}
}

// MockStepMockRecorder is the mock recorder for MockStep.
type MockStepMockRecorder struct {
	mock *MockStep
}

// NewMockStep creates a new mock instance.
func NewMockStep(ctrl *gomock.Controller) *MockStep {
	mock := &MockStep{ctrl: ctrl}
	mock.recorder = &MockStepMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStep) EXPECT() *MockStepMockRecorder {
	return m.recorder
}

// Compensate mocks base method.
func (m *MockStep) Compensate(ctx context.Context, saga *domain.Saga, order *domain.Order, idempotencyKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Compensate", ctx, saga, order, idempotencyKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// Compensate indicates an expected call of Compensate.
func (mr *MockStepMockRecorder) Compensate(ctx, saga, order, idempotencyKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Compensate", reflect.TypeOf((*MockStep)(nil).Compensate), ctx, saga, order, idempotencyKey)
}

// Execute mocks base method.
func (m *MockStep) Execute(ctx context.Context, saga *domain.Saga, order *domain.Order, idempotencyKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, saga, order, idempotencyKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockStepMockRecorder) Execute(ctx, saga, order, idempotencyKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockStep)(nil).Execute), ctx, saga, order, idempotencyKey)
}

// Name mocks base method.
func (m *MockStep) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockStepMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockStep)(nil).Name))
}

// MockPreparable is a mock of Preparable interface.
type MockPreparable struct {
	ctrl     *gomock.Controller
	recorder *MockPreparableMockRecorder
	isgomock struct{}
}

// MockPreparableMockRecorder is the mock recorder for MockPreparable.
type MockPreparableMockRecorder struct {
	mock *MockPreparable
}

// NewMockPreparable creates a new mock instance.
func NewMockPreparable(ctrl *gomock.Controller) *MockPreparable {
	mock := &MockPreparable{ctrl: ctrl}
	mock.recorder = &MockPreparableMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPreparable) EXPECT() *MockPreparableMockRecorder {
	return m.recorder
}

// Prepare mocks base method.
func (m *MockPreparable) Prepare(saga *domain.Saga) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Prepare", saga)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Prepare indicates an expected call of Prepare.
func (mr *MockPreparableMockRecorder) Prepare(saga any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Prepare", reflect.TypeOf((*MockPreparable)(nil).Prepare), saga)
}
