// Code generated by MockGen. DO NOT EDIT.
// Source: ../internal/saga/compensator/compensator.go
//
// Generated by this command:
//
//	mockgen -source=../internal/saga/compensator/compensator.go -package=mocks -destination=mock_saga_compensator.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	domain "github.com/ekhodzitsky/go-ozon-marketplace/services/order-service/internal/domain"
	steps "github.com/ekhodzitsky/go-ozon-marketplace/services/order-service/internal/saga/steps"
	gomock "go.uber.org/mock/gomock"
)

// MockCompensationPlanner is a mock of CompensationPlanner interface.
type MockCompensationPlanner struct {
	ctrl     *gomock.Controller
	recorder *MockCompensationPlannerMockRecorder
	isgomock struct{}
}

// MockCompensationPlannerMockRecorder is the mock recorder for MockCompensationPlanner.
type MockCompensationPlannerMockRecorder struct {
	mock *MockCompensationPlanner
}

// NewMockCompensationPlanner creates a new mock instance.
func NewMockCompensationPlanner(ctrl *gomock.Controller) *MockCompensationPlanner {
	mock := &MockCompensationPlanner{ctrl: ctrl}
	mock.recorder = &MockCompensationPlannerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCompensationPlanner) EXPECT() *MockCompensationPlannerMockRecorder {
	return m.recorder
}

// Plan mocks base method.
func (m *MockCompensationPlanner) Plan(saga *domain.Saga, failed steps.Step) []steps.Step {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Plan", saga, failed)
	ret0, _ := ret[0].([]steps.Step)
	return ret0
}

// Plan indicates an expected call of Plan.
func (mr *MockCompensationPlannerMockRecorder) Plan(saga, failed any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Plan", reflect.TypeOf((*MockCompensationPlanner)(nil).Plan), saga, failed)
}
