// Code generated by MockGen. DO NOT EDIT.
// Source: ../internal/unitofwork/uow.go
//
// Generated by this command:
//
//	mockgen -source=../internal/unitofwork/uow.go -package=mocks -destination=mock_unitofwork.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	repository "github.com/ekhodzitsky/go-ozon-marketplace/services/order-service/internal/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockUnitOfWork is a mock of UnitOfWork interface.
type MockUnitOfWork struct {
	ctrl     *gomock.Controller
	recorder *MockUnitOfWorkMockRecorder
	isgomock struct{}
}

// MockUnitOfWorkMockRecorder is the mock recorder for MockUnitOfWork.
type MockUnitOfWorkMockRecorder struct {
	mock *MockUnitOfWork
}

// NewMockUnitOfWork creates a new mock instance.
func NewMockUnitOfWork(ctrl *gomock.Controller) *MockUnitOfWork {
	mock := &MockUnitOfWork{ctrl: ctrl}
	mock.recorder = &MockUnitOfWorkMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnitOfWork) EXPECT() *MockUnitOfWorkMockRecorder {
	return m.recorder
}

// OrderRepo mocks base method.
func (m *MockUnitOfWork) OrderRepo() repository.OrderRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OrderRepo")
	ret0, _ := ret[0].(repository.OrderRepository)
	return ret0
}

// OrderRepo indicates an expected call of OrderRepo.
func (mr *MockUnitOfWorkMockRecorder) OrderRepo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OrderRepo", reflect.TypeOf((*MockUnitOfWork)(nil).OrderRepo))
}

// OutboxRepo mocks base method.
func (m *MockUnitOfWork) OutboxRepo() repository.OutboxRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OutboxRepo")
	ret0, _ := ret[0].(repository.OutboxRepository)
	return ret0
}

// OutboxRepo indicates an expected call of OutboxRepo.
func (mr *MockUnitOfWorkMockRecorder) OutboxRepo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OutboxRepo", reflect.TypeOf((*MockUnitOfWork)(nil).OutboxRepo))
}
