// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ekhodzitsky/go-ozon-marketplace/api/gen/go/inventory/v1 (interfaces: InventoryServiceClient)
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=mock_inventory_service_client.go github.com/ekhodzitsky/go-ozon-marketplace/api/gen/go/inventory/v1 InventoryServiceClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	inventoryv1 "github.com/ekhodzitsky/go-ozon-marketplace/api/gen/go/inventory/v1"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockInventoryServiceClient is a mock of InventoryServiceClient interface.
type MockInventoryServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockInventoryServiceClientMockRecorder
	isgomock struct{}
}

// MockInventoryServiceClientMockRecorder is the mock recorder for MockInventoryServiceClient.
type MockInventoryServiceClientMockRecorder struct {
	mock *MockInventoryServiceClient
}

// NewMockInventoryServiceClient creates a new mock instance.
func NewMockInventoryServiceClient(ctrl *gomock.Controller) *MockInventoryServiceClient {
	mock := &MockInventoryServiceClient{ctrl: ctrl}
	mock.recorder = &MockInventoryServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInventoryServiceClient) EXPECT() *MockInventoryServiceClientMockRecorder {
	return m.recorder
}

// GetLedger mocks base method.
func (m *MockInventoryServiceClient) GetLedger(ctx context.Context, in *inventoryv1.GetLedgerRequest, opts ...grpc.CallOption) (*inventoryv1.GetLedgerResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetLedger", varargs...)
	ret0, _ := ret[0].(*inventoryv1.GetLedgerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLedger indicates an expected call of GetLedger.
func (mr *MockInventoryServiceClientMockRecorder) GetLedger(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLedger", reflect.TypeOf((*MockInventoryServiceClient)(nil).GetLedger), varargs...)
}

// GetStock mocks base method.
func (m *MockInventoryServiceClient) GetStock(ctx context.Context, in *inventoryv1.GetStockRequest, opts ...grpc.CallOption) (*inventoryv1.GetStockResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetStock", varargs...)
	ret0, _ := ret[0].(*inventoryv1.GetStockResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStock indicates an expected call of GetStock.
func (mr *MockInventoryServiceClientMockRecorder) GetStock(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStock", reflect.TypeOf((*MockInventoryServiceClient)(nil).GetStock), varargs...)
}

// Release mocks base method.
func (m *MockInventoryServiceClient) Release(ctx context.Context, in *inventoryv1.ReleaseRequest, opts ...grpc.CallOption) (*inventoryv1.ReleaseResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Release", varargs...)
	ret0, _ := ret[0].(*inventoryv1.ReleaseResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Release indicates an expected call of Release.
func (mr *MockInventoryServiceClientMockRecorder) Release(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockInventoryServiceClient)(nil).Release), varargs...)
}

// Reserve mocks base method.
func (m *MockInventoryServiceClient) Reserve(ctx context.Context, in *inventoryv1.ReserveRequest, opts ...grpc.CallOption) (*inventoryv1.ReserveResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Reserve", varargs...)
	ret0, _ := ret[0].(*inventoryv1.ReserveResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reserve indicates an expected call of Reserve.
func (mr *MockInventoryServiceClientMockRecorder) Reserve(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reserve", reflect.TypeOf((*MockInventoryServiceClient)(nil).Reserve), varargs...)
}
