// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ekhodzitsky/go-ozon-marketplace/api/gen/go/catalog/v1 (interfaces: CatalogServiceClient)
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=mock_catalog_service_client.go github.com/ekhodzitsky/go-ozon-marketplace/api/gen/go/catalog/v1 CatalogServiceClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	catalogv1 "github.com/ekhodzitsky/go-ozon-marketplace/api/gen/go/catalog/v1"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockCatalogServiceClient is a mock of CatalogServiceClient interface.
type MockCatalogServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockCatalogServiceClientMockRecorder
	isgomock struct{}
}

// MockCatalogServiceClientMockRecorder is the mock recorder for MockCatalogServiceClient.
type MockCatalogServiceClientMockRecorder struct {
	mock *MockCatalogServiceClient
}

// NewMockCatalogServiceClient creates a new mock instance.
func NewMockCatalogServiceClient(ctrl *gomock.Controller) *MockCatalogServiceClient {
	mock := &MockCatalogServiceClient{ctrl: ctrl}
	mock.recorder = &MockCatalogServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCatalogServiceClient) EXPECT() *MockCatalogServiceClientMockRecorder {
	return m.recorder
}

// CreateProduct mocks base method.
func (m *MockCatalogServiceClient) CreateProduct(ctx context.Context, in *catalogv1.CreateProductRequest, opts ...grpc.CallOption) (*catalogv1.CreateProductResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateProduct", varargs...)
	ret0, _ := ret[0].(*catalogv1.CreateProductResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProduct indicates an expected call of CreateProduct.
func (mr *MockCatalogServiceClientMockRecorder) CreateProduct(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProduct", reflect.TypeOf((*MockCatalogServiceClient)(nil).CreateProduct), varargs...)
}

// DeleteProduct mocks base method.
func (m *MockCatalogServiceClient) DeleteProduct(ctx context.Context, in *catalogv1.DeleteProductRequest, opts ...grpc.CallOption) (*catalogv1.DeleteProductResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteProduct", varargs...)
	ret0, _ := ret[0].(*catalogv1.DeleteProductResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteProduct indicates an expected call of DeleteProduct.
func (mr *MockCatalogServiceClientMockRecorder) DeleteProduct(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProduct", reflect.TypeOf((*MockCatalogServiceClient)(nil).DeleteProduct), varargs...)
}

// GetProduct mocks base method.
func (m *MockCatalogServiceClient) GetProduct(ctx context.Context, in *catalogv1.GetProductRequest, opts ...grpc.CallOption) (*catalogv1.GetProductResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetProduct", varargs...)
	ret0, _ := ret[0].(*catalogv1.GetProductResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProduct indicates an expected call of GetProduct.
func (mr *MockCatalogServiceClientMockRecorder) GetProduct(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProduct", reflect.TypeOf((*MockCatalogServiceClient)(nil).GetProduct), varargs...)
}

// ListProducts mocks base method.
func (m *MockCatalogServiceClient) ListProducts(ctx context.Context, in *catalogv1.ListProductsRequest, opts ...grpc.CallOption) (*catalogv1.ListProductsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListProducts", varargs...)
	ret0, _ := ret[0].(*catalogv1.ListProductsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProducts indicates an expected call of ListProducts.
func (mr *MockCatalogServiceClientMockRecorder) ListProducts(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProducts", reflect.TypeOf((*MockCatalogServiceClient)(nil).ListProducts), varargs...)
}

// SearchProducts mocks base method.
func (m *MockCatalogServiceClient) SearchProducts(ctx context.Context, in *catalogv1.SearchProductsRequest, opts ...grpc.CallOption) (*catalogv1.SearchProductsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SearchProducts", varargs...)
	ret0, _ := ret[0].(*catalogv1.SearchProductsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchProducts indicates an expected call of SearchProducts.
func (mr *MockCatalogServiceClientMockRecorder) SearchProducts(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchProducts", reflect.TypeOf((*MockCatalogServiceClient)(nil).SearchProducts), varargs...)
}

// UpdateProduct mocks base method.
func (m *MockCatalogServiceClient) UpdateProduct(ctx context.Context, in *catalogv1.UpdateProductRequest, opts ...grpc.CallOption) (*catalogv1.UpdateProductResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateProduct", varargs...)
	ret0, _ := ret[0].(*catalogv1.UpdateProductResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProduct indicates an expected call of UpdateProduct.
func (mr *MockCatalogServiceClientMockRecorder) UpdateProduct(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProduct", reflect.TypeOf((*MockCatalogServiceClient)(nil).UpdateProduct), varargs...)
}
